# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Architek3D
description: >- # this means to ignore newlines until "baseurl:"
  Somos una empresa líder en la impresión 3D para la construcción en México, Utilizamos robots de impresión 3D de última generación para crear estructuras aún más complejas y detalladas con una precisión sin precedentes. Nuestros robots están diseñados para trabajar en conjunto con nuestro equipo de expertos en construcción y diseño, lo que nos permite crear proyectos innovadores y personalizados que se adaptan a las necesidades específicas de nuestros clientes. La impresión robótica 3D nos permite imprimir grandes estructuras en un tiempo récord y con una calidad excepcional, lo que reduce significativamente los costos y el tiempo de construcción. Ya sea que esté buscando construir una casa, una estructura comercial o cualquier otro tipo de edificio, nuestro equipo de profesionales puede ayudarlo a llevar su proyecto al siguiente nivel. Contáctenos hoy mismo para conocer más sobre nuestros servicios de impresión robótica 3D y cómo podemos ayudarlo a hacer realidad su visión.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://architek3d.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

email:              neobrutal.studio@gmail.com
#twitter:            luigipaal
#facebook:           luigipacheco
github-url:         luigipacheco
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           luis-arturo-pacheco-16970a71
#xing:              username
instagram:          architekmx
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              luigi_pacheco
#dribbble:          username
#youtube:           luigipach
#youtube-channel:   luigipach
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#portfolio:         www.neobrutal.com
